typography_spectrum: 0.06647
color:
  brandColors:
    - '#f4306e'
    - '#fbf31c'
    - '#000000'
    - '#a69f9c'
    - '#48e513'
  brandStrength: 0.5
  lightness: 0.43995096627622843
  saturation: 0.5
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: The C & T Family
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Cravens and Taylor Famly
description: 2015-
purpose: []
