name: 'The C & T Family'
favicon: null
layout_spectrum: 0.010888478951528668
typography_spectrum: 0.06647
title: Cravens and Taylor Famly
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cbcbc1'
    - '#665e69'
    - '#171f36'
    - '#01cbea'
    - '#b50024'
  brandStrength: 0.75
  lightness: 0.43995096627622843
  saturation: 0.3125
  rhythmicContrast: 0.854446655139327
purpose: []
