name: 'The C & T Family'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.06647
title: Cravens and Taylor Famly
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4306e'
    - '#fbf31c'
    - '#000000'
    - '#a69f9c'
    - '#48e513'
  brandStrength: 0.5
  lightness: 0.43995096627622843
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
